### ISSUE TITLE
Update foreign/hpm-downloader submodule with latest fixes

### ISSUE THREAD

**Issue by guilhermerc** [lnls-dig/bpm-cfg#4]
Some tweaks on [https://github.com/lnls-dig/bpm-cfg/blob/master/03-mmc-configure/mmc-configure.sh](https://github.com/lnls-dig/bpm-cfg/blob/master/03-mmc-configure/mmc-configure.sh) may be needed.

**Comment by augustofg** [comment]
Not applicable anymore.
